version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"

    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul

  security-session-redis:
    container_name: security-session-redis
    build: .
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"

    ports:
      - "8081:8081"
    depends_on:
      - mariadb