version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"

    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul

  interceptor:
    container_name: interceptor
    build: .
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"

    ports:
      - "8080:8080"
    depends_on:
      - mariadb
