server:
  servlet:
    session:
      cookie:
        name: JSESSIONID

spring:
  application:
    name: login

  session:
    store-type: redis
    redis:
      namespace: shboard:session

  data:
    redis:
      host: localhost
      password: 1234
      port: 6379

  datasource:
    url: jdbc:h2:tcp://localhost/~/performance_test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug

