spring:
  profiles:
    active: local

---

#로컬
spring:
  config:
    activate:
      on-profile: local

  application:
    name: login

#  data:
#    redis:
#      host: localhost
#      password: 1234
#      port: 6379

  datasource:
    url: jdbc:h2:tcp://localhost/~/performance_test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  tomcat:
    mbeanregistry:
      enabled: true

  port: 8081

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret_key: login_performance_test
  access_token_validity: 1800
