spring:
  profiles:
    active: local

---

#로컬
spring:
  config:
    activate:
      on-profile: local

  application:
    name: login

  data:
    redis:
      host: localhost
      password: 1234
      port: 6379

  datasource:
    url: jdbc:h2:tcp://localhost/~/performance_test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  tomcat:
    mbeanregistry:
      enabled: true

  port: 8081

  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
      timeout: 3600 # 세션의 유효 시간을 지정합니다. 단위는 초입니다.


logging.level:
  org.hibernate.SQL: debug

---
#도커

spring:
  config:
    activate:
      on-profile: security-session-redis

  application:
    name: login

  data:
    redis:
      host: localhost
      password:
      port: 6379

  datasource:
    url: jdbc:mariadb://mariadb:3306/performance_test
    username: sami355
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  tomcat:
    mbeanregistry:
      enabled: true

  servlet:
    session:
      cookie:
        name: JSESSIONID

  port: 8081

logging.level:
  org.hibernate.SQL: debug